using System;
using System.Windows.Forms;
using System.Drawing;
using System.IO;
using System.Collections.Generic;
using System.Net;
using CefSharp.WinForms;

namespace JH.Applications
{
    public partial class FormMain : Form
    {
        string token;
        string tokenPath;
        string mapCalibrationPath;
        string projectFolder;
        string resultFolder;
        string resultFile;
        string esultSortedFile;
        string photoPath;
        StreamWriter resultFileWriter;
        StreamWriter resultFileSortedWriter;
        bool searching;
        bool searchStopped = true;
        bool downloadPictures;
        List<string> urlHistory;
        int urlHistoryPointer=-1;
        bool addToUrlHistory;
        double neLat;
        double neLng;
        double swLat;
        double swLng;
        int neZoom;
        int swZoom;
        double deltaLat = 300;
        double deltaLng = 1360;
        Size sizeWebBrowserBefore;
        List<ItemList> resultList;
        ItemList itemList;
        string lastUrlPath;
        string lastUrlString;
        SearchDialog searchDialog;
        public SearchCondition[] searchCondition;
        public SearchCondition[] searchConditionShadow;
        string freetext = "";
        string location = "";
        string building = "";
        string person = "";
        string notBefore = "";
        string notAfter = "";
        int startExt;
        int circle;
        int maxCircle;
        string results = "Results";
        string luftfoto = "Luftfoto";
        string searchResult = "SearchResult";
        string sortedResult = "Metadata";
        string ext;
        string exttxt;
        bool kbServerRunning;
        ChromiumWebBrowser webBrowser;
        WebClient webClient;
        string vejnavn;
        string husnummer;
        string postnummer;
        string betegnelse;
        string lokalitet;
        string by;
        string sogn;
        string kommune;
        string politikreds;
        string retskreds;
        string region;
        string ejerlav;
        string matrikelnr;
        string zone;
        string primnavn;
        string koordinat;
        DataforsyningAdresser dataforsyningAdresser;
        DataforsyningSteder dataforsyningSteder;
        string vejnavnKB;
        string husnummerKB;
        string postnummerKB;
        string matrikelnummerKB;
        string ejerlavKB;
        string kommuneKB;
        string sognKB;
        string bygningsnavnKB;
        string byKB;
        string kbdbResponse;
        double[] avgCoordinate;
        List<BatchInput> batchInput;
        List<double[]> batchCoordinates;
        bool batchProcessing;
        string queryString;
        double avgCircle;
        double avgTimePerDownload;
    }
}